apiVersion: apps/v1
kind: Deployment
metadata:
  name: clp-app-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clp-app-client
  template:
    metadata:
      labels:
        app: clp-app-client
    spec:
      containers:
        - name: clp-app-client
          image: clp-app-client
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: clp-app-client
spec:
  type: NodePort
  selector:
    app: clp-app-client
  ports:
    - port: 5173
      protocol: TCP
      targetPort: 5173
      nodePort: 31000
